language:    # 指明使用的语言
  - go

go:          # 语言版本号
  - "1.12"   # 默认使用最新版本,注意，需要 "1.10" 版本的时候必须表示为字符串形式，如果写成 1.10 则会使用 1.1 版本;x表示对应前缀的最新版本

os:
  - linux
  - osx

script:      # 执行的脚步，但是go默认会执行下面的这些命令的，所以可以不用写
  #- go get -v
  - ls
  - export GO111MODULE=on
  - echo $GOPATH
  - echo $PWD
  - cd $GOPATH/src/github.com/goex-top/market_data_collector
  - echo $PWD
  - make
#  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
#
#after_success:
#  - bash <(curl -s https://codecov.io/bash)