---
subs:
  - exchange_name: Binance
    currency_pair: BTC_USDT
    period: 100
    flag: 2
  - exchange_name: Swap_Binance
    currency_pair: BTC_USDT
    contract_type: swap
    period: 100
    flag: 2
store:
  csv: false
  influx_db: true
  influx_db_cfg:
    url: http://localhost:8086
    database: market_data
with_market_center: true
market_center_path: "/tmp/goex.market.center"
